name: Metrics - Habits

on:
  schedule:
    - cron: "0 1 * * *"  # Ejecutar diariamente a la 01:00 UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (requerido por GitHub Actions)
        uses: actions/checkout@v4

      - name: Generate recent activity charts
        uses: lowlighter/metrics@latest
        with:
          # Archivo de salida
          filename: metrics.plugin.habits.charts.svg

          # Token de acceso personal con los permisos requeridos
          token: ${{ secrets.METRICS_TOKEN }}

          # Configuración base (vacía para solo usar plugins)
          base: ""

          # Configuración de plugin habits
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: no

          # Opcional: para mayor precisión sin ralentizar demasiado
          plugin_habits_from: 300
          plugin_habits_days: 14
          plugin_habits_trim: yes
          plugin_habits_charts_type: graph

          # Configurar zona horaria adecuada
          config_timezone: America/Lima  # o Europe/Paris, según preferencia
